[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pui?$'
extend-exclude = '''
# A regex for excluding files or directories from formatting
/(
      \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
)/
'''
