name: Team Management
description: Create, update, or remove GitHub teams, members and repository access
title: "[Team Management] "
labels: ["team-management"]
assignees:
  - octocat

body:
  - type: dropdown
    id: action
    attributes:
      label: Action
      description: What action would you like to perform?
      options:
        - create
        - update
        - remove
    validations:
      required: true

  - type: input
    id: team_name
    attributes:
      label: Team Name
      description: Name of the parent team
      placeholder: example-team
    validations:
      required: true

  - type: input
    id: project
    attributes:
      label: Project Name
      description: Name of the project this team is for (only required for team creation, cannot be changed later)
      placeholder: Example Project
    validations:
      required: false

  - type: textarea
    id: team_description
    attributes:
      label: Team Description
      description: Description of the parent team (only required for team creation, cannot be changed later)
      placeholder: Team responsible for the example project
    validations:
      required: false

  - type: textarea
    id: members
    attributes:
      label: Members
      description: List of members to update/remove followed by list of child teams to add the users too all will update/remove the user to all teams (format @username (developers, testers) or @username (all))
      placeholder: |
        - @John-Doe_pgh (developers, testers)
        - @Jane-Doe_pgh (all)
    validations:
      required: false

  - type: textarea
    id: repositories
    attributes:
      label: Repositories
      description: List of repositories to update/remove
      placeholder: |
        - repo1
        - repo2
    validations:
      required: false

  - type: textarea
    id: child_teams
    attributes:
      label: Child Teams
      description: List of child teams to update/remove (format - child-team1:description:repository_permissions) repository_permissions to be one of read (default), write, triage, maintain or admin 
      placeholder: |
        - child-team1:Team responsible for requirment:read
        - child-team2:Team responsible for requirment:write
    validations:
      required: false
