name: Process Team Management Issue

on:
  issues:
    types: [opened, edited]

jobs:
  process-team-issue:
    if: contains(github.event.issue.labels.*.name, 'team-management')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    environment: 
      name: test-env
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
          owner: ${{ github.repository_owner }}
          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML requests

      - name: Process team issue
        id: process-issue
        run: python scripts/process_team_issue.py
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token  }}
          GITHUB_ORG: ${{ github.repository_owner }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_BODY: ${{ toJSON(github.event.issue.body) }}
          ISSUE_TITLE: ${{ toJSON(github.event.issue.title) }}
          REPO: ${{ github.repository }}

      - name: Commit changes if necessary
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          echo "Checking for changes in teams directory"
          git add teams/
          
          # Show what files were modified
          git status --porcelain
          
          # Force detection of changes even if whitespace or formatting is similar
          CHANGES=$(git status --porcelain teams/)
          if [ -z "$CHANGES" ]; then
            echo "No changes detected in teams directory"
            exit 0
          fi
          
          echo "Changes detected, committing..."
          git commit -m "Update team configuration from issue #${{ github.event.issue.number }}"
          git push
