name: Sync GitHub Teams

on:
  push:
    branches:
      - main
    paths:
      - 'teams/*/teams.yml'
  workflow_dispatch:
    inputs:
      team:
        description: 'Team to sync (leave empty to sync all teams)'
        required: false
        default: ''

jobs:
  sync-teams:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: test-env
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML requests

      - name: Sync GitHub teams
        run: python scripts/sync_github_teams.py ${{ github.event.inputs.team != '' && format('--team {0}', github.event.inputs.team) || '' }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_ORG: ${{ github.repository_owner }}
